version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    working_directory: ~/src/jsonrest-go
    steps:
      - restore_cache:
          keys:
            - v1-pkg-cache
      - checkout
      - run: make setup
      - run: make install
      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"

  lint:
    docker:
      - image: circleci/golang:1.13
    working_directory: ~/src/jsonrest-go
    steps:
      - checkout
      - run: make setup
      - run: make lint

  test:
    docker:
      - image: circleci/golang:1.13
    working_directory: ~/src/jsonrest-go
    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS
      - run: make setup
      - run: go get github.com/jstemmer/go-junit-report
      - run:
          name: Run unit tests
          command: |
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            go test -v ./... | tee ${TEST_RESULTS}/go-test.out
      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output
      - store_test_results:
          path: /tmp/test-results

  release:
    docker:
      - image: deliveroo/semantic-release:1.0.0
    steps:
      - checkout
      - run: semantic-release -r ${CIRCLE_REPOSITORY_URL}

  commitlint:
    docker:
      - image: deliveroo/semantic-release:1.0.0
    steps:
      - checkout
      - run: commitlint --from $(git rev-parse origin/master) --to $CIRCLE_SHA1 --verbose

workflows:
  version: 2
  all:
    jobs:
      - build
      - commitlint
      - lint
      - test
      - release:
          requires:
            - build
            - lint
            - commitlint
            - test
          filters:
            branches:
              only:
                - master
